sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
notifications:
  email: false
service_name: travis-pro
repo_token: Aib0NGZu5010HdYWa5LGw2IngqfA1730S
