export const FETCH_ALLGAMES_SUCCESS = 'FETCH_ALLGAMES_SUCCESS';
export const FETCH_ALLGAMES_ERROR = 'FETCH_ALLGAMES_ERROR';

export const FETCH_GAME_DETAILS_SUCCESS = 'FETCH_GAME_DETAILS_SUCCESS';
export const FETCH_GAME_DETAILS_ERROR = 'FETCH_GAME_DETAILS_ERROR';

export const FETCH_CREATORS_SUCCESS = 'FETCH_CREATORS_SUCCESS';
export const FETCH_CREATORS_ERROR = 'FETCH_CREATORS_ERROR';

export const FETCH_CREATORS_DETAILS_SUCCESS = 'FETCH_CREATORS_DETAILS_SUCCESS';
export const FETCH_CREATORS_DETAILS_ERROR = 'FETCH_CREATORS_DETAILS_ERROR';

export const FETCH_ALL_TAGS_SUCCESS = 'FETCH_ALL_TAGS_SUCCESS';
export const FETCH_ALL_TAGS_ERROR = 'FETCH_ALL_TAGS_ERROR';

export const FETCH_TAGS_DETAILS_SUCCESS = 'FETCH_TAGS_DETAILS_SUCCESS';
export const FETCH_TAGS_DETAILS_ERROR = 'FETCH_TAGS_DETAILS_ERROR';

export const FETCH_ALLSTORES_SUCCESS = 'FETCH_ALLSTORES_SUCCESS';
export const FETCH_ALLSTORES_ERROR = 'FETCH_ALLSTORES_ERROR';